### ISSUE TITLE
Creating new label from note with default color will set color wrong on note

### ISSUE THREAD

**Issue by ai-tran** [jmanke/dash#26]
![image](https://user-images.githubusercontent.com/13632125/222805880-627827dc-394f-4b01-bc16-8d3427e51f59.png)
![image](https://user-images.githubusercontent.com/13632125/222806056-9564a68d-cae8-4638-9f9f-492f2c7510b2.png)

**Comment by jmanke** [comment]
I don't believe this is a bug anymore. Let me know if you see it again.

@ai-tran
