### ISSUE TITLE
Allow labels to be rearrangeable 

### ISSUE THREAD

**Issue by ai-tran** [jmanke/dash#27]
![image](https://user-images.githubusercontent.com/13632125/222807522-61b9635a-447b-461b-8a29-4c292afc39e1.png)

**Comment by jmanke** [comment]
Should they be draggable to sort, or some other UI?

**Comment by jmanke** [comment]
Draggable it is

**Comment by jmanke** [comment]
<img width="641" alt="Screenshot 2023-03-03 at 5 40 12 PM" src="https://user-images.githubusercontent.com/19629809/222868857-592084e3-5ecb-4da6-a09e-f41748067682.png">

**Comment by jmanke** [comment]
Nice tutorial for the look we want https://baseweb.design/blog/drag-and-drop-list/

**Comment by jmanke** [comment]
@ai-tran Ready to test here https://dashboard.heroku.com/apps/hellodash-frontend-2x

**Comment by jmanke** [comment]
Released in prod
